version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - eco_network

  redis:
    image: redis:7.0
    container_name: redisdb
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    environment:
      - REDIS_PASSWORD=password
    networks:
      - eco_network
  
  # kafka:
  #   image: bitnami/kafka:3.6
  #   container_name: kafka
  #   ports:
  #     - 9092:9092
  #   # volumes:
  #   #   - ./data/kafka:/bitnami
  #   environment:
  #     # - ALLOW_PLAINTEXT_LISTENER=yes
  #     # - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
  #     # KRaft settings
  #     - KAFKA_CFG_NODE_ID=0
  #     - KAFKA_CFG_PROCESS_ROLES=controller,broker
  #     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
  #     # Listeners
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
  #     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  #     - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
  #   networks:
  #     - eco_network

networks:
  eco_network:
    name: eco_network
    driver: bridge

