version: "3.8"
services:
  mongo:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - eco_network

  redis:
    image: redis:7.0
    container_name: redisdb
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    environment:
      - REDIS_PASSWORD=password
    networks:
      - eco_network
  
  # kafka:
  #   image: bitnami/kafka:3.6
  #   container_name: kafka
  #   ports:
  #     - 9092:9092
  #   # volumes:
  #   #   - ./data/kafka:/bitnami
  #   environment:
  #     # - ALLOW_PLAINTEXT_LISTENER=yes
  #     # - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
  #     # KRaft settings
  #     - KAFKA_CFG_NODE_ID=0
  #     - KAFKA_CFG_PROCESS_ROLES=controller,broker
  #     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
  #     # Listeners
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
  #     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  #     - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
  #   networks:
  #     - eco_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/
      - ./logs/rabbitmq:/var/log/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - eco_network

  mysql_master:
    image: mysql:8.0
    container_name: mysql_master
    env_file:
      - ./mysql/master/mysql_master.env
    ports:
      - "4406:3306"
    volumes:
      - ./mysql/master/data:/var/lib/mysql
      - ./mysql/master/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
    networks:
      - eco_network

  mysql_slave:
    image: mysql:8.0
    container_name: mysql_slave
    env_file:
      - ./mysql/slave/mysql_slave.env
    ports:
      - "5506:3306"
    volumes:
      - ./mysql/slave/data:/var/lib/mysql
      - ./mysql/slave/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
    networks:
      - eco_network

networks:
  eco_network:
    name: eco_network
    driver: bridge

