version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - mongo_network
networks:
  mongo_network:
    name: mongo_network
    driver: bridge